# Generated by Django 3.0.7 on 2020-07-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
