# Generated by Django 3.0.7 on 2020-07-18 17:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='noticia',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='noticias_search_vector_idx'),
        ),
    ]
