# Generated by Django 3.0.7 on 2020-07-18 17:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurimetria', '0003_auto_20200711_1046'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sentenca',
            name='search_vector_idx',
        ),
        migrations.AddIndex(
            model_name='sentenca',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='jurimetria_search_vector_idx'),
        ),
    ]
