# Generated by Django 3.0.8 on 2020-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('sigla', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=10)),
                ('site_principal', models.URLField()),
                ('site_busca_1_f', models.URLField()),
                ('site_busca_2_f', models.URLField()),
                ('site_busca_1_e', models.URLField()),
                ('site_busca_2_e', models.URLField()),
            ],
        ),
    ]
